branches:
  only: master
  except: master
  publish: True
releases: True
domains:
- schema:
    url: https://github.com/hugdru/schemas/blob/master/big_data-schema.yaml
  data:
    Scalability:
      Scalable Distribution Architecture: [horizontal partitioning of database, horizontal partitioning and replication]
      Scaling Out - Adding Data Storage Capacity: automatic data rebalancing
      Request Load Balancing: fixed connections to a request coordinator
      Granularity of Write Locks: locks on updated objects only
      Scalable Request Processing Architecture: centralized coordinator, but can be replicated
    Consistency:
      Object Level Atomic Updates: supported
      ACID Transactions: lightweight transactions (e.g. compare and set)
      Distributed Transactions: not supported
      Durable Writes: supported
      Quorum Reads and Writes: not supported
      Number of Replicas to Read: not supported
      Number of Replicas to Write: not supported
      Writes with Unavailable Replicas: no rollback - write returns replication error
      Read from Master Only: specified in the database configuration
      Resolving Write Conflicts: not applicable - master-slave
    Query Language:
      API-based: supported
      Declarative Query Language: not supported
      REST/HTTP-based Queries: not supported
      Languages Supported: [Java, Python, PHP, Ruby]
      Cursor-based Queries: supported
      JOIN-style queries: not supported
      Complex Data Types: [none]
      Restrict Query Result Set Size: supported
      Key Matching Options: [exact]
      Sort Options: [ascending]
      Triggers: [not supported]
      Data Object Expiry: supported
    Data Model:
      Data Model: Column
      Fixed Schema: not required
      Opaque Data Objects: not required
      Hierarchical Data Objects: not supported
      Automatically allocated Primary Key: not supported
      Composite Keys: not supported
      Secondary Indexes: supported
      Query by Key Ranges: supported
      Query by Partial Keys: not supported
      Query by Non-key Values: supported
      Map Reduce API: builtin
      Indexed Text Search: not supported
    Data Replication:
      Replication Architecture: master-slave
      Replication for Backup: not supported
      Replication across Data Centers: supported by data center aware features
      Replica Writes: [to master replica only]
      Replica Reads: [from master replica only]
      Read Repair: not relevant
      Automatic Replica Failure Detection: supported
      Automatic Failover: supported
      Automatic New Master Election after Failure: supported
      Replica Recovery and Resynchronization: supported - automatic
    Data Distribution:
      Data Distribution Architecture: [master-single slave, master-multiple slaves]
      Data Distribution Method: [assigned key ranges to nodes]
      Automatic Data Rebalancing: [new storage triggered]
      Physical Data Distribution: [single cluster, rack-aware on single cluster]
      Query Architecture: direct shard connection only (resolved in client)
      Queries using Non-Shard Key Value: [not supported]
      Merging Query Results from Multiple Shards: [random order]
    Security:
      Client Authentication: [custom user/password]
      Server Authentication: [shared keyfile]
      Credential Store: external file
      Role Based Security: supported
      Security Role Options: [custom roles]
      Scope of Roles: [collection, field]
      Database Encryption: supported
      Logging: [fixed event logging]
    Admin:
      Configuration Files: multiple
      Node command line access: authenticated
      Node addition/removal: [centralized tool]
      Cluster monitoring: [snapshot]
      Dump database configuration: supported
      Database object count: supported
      Physical storage usage: supported
